# -*- coding: utf-8 -*-
"""bucle_for_basico1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TJ0hRm_gE1y0vtxhhnFpRHMg7Q5wdBS9
"""

# Básico: Imprimir todos los números enteros del 0 al 100
numero = 0
while numero < 101:
  print(numero)
  numero += 1
else:
  print("- Todos los números enteros, hasta el 100, impresos")

# Múltiplos de 2
numero = 0
while numero < 501:
  if numero % 2 == 0:
    print(numero)
  numero += 1
else:
  print("- Todos los números múltiplos de 2, hasta el 500, impresos")

# Contar Vanilla Ice
for numero in range (1,101): # Nros enteros del 1 al 100
  if numero % 10 == 0: # divisible por 10
    print("baby")
  elif numero % 5 == 0: # divisible por 5
    print("ice ice") # Primero 10, sino tomará solo los 5s.
  else:
    print(numero)

# Número gigante (sumar pares del 0 al 500.000 e imprimir suma total)
suma = 0

for numero in range (0,500001, 2): # Consideramos solo pares entre el 0 y 500.000
    suma += numero # a cada suma se le agrega el nuevo valor par, hasta el último
print(suma)

# Regresame al 3: Nros positivos comenzando desde 2024 en cuenta regresiva de 3 en 3
cuenta= 2024

while cuenta >= 0:
  if cuenta % 3 == 0:
    print(cuenta)
  cuenta -= 1

# Contador dinámico
numInicial = 3
numFinal = 10
multiplo = 2

for numero in range(numInicial, numFinal+1): # +1 para que considere hasta numFinal
    if numero % multiplo == 0:
        print(numero)

