# -*- coding: utf-8 -*-
"""funciones_intermedias_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bKzEa2J-5u2bhOJlN98NhJbEvVvHaIXK
"""

# Datos Originales
matriz = [ [10, 15, 20], [3, 7, 14] ]
cantantes = [
    {"nombre": "Ricky Martin", "pais": "Puerto Rico"},
    {"nombre": "Chayanne", "pais": "Puerto Rico"}
]

ciudades = {
    "México": ["Ciudad de México", "Guadalajara", "Cancún"],
    "Chile": ["Santiago", "Concepción", "Viña del Mar"]
}

coordenadas = [
    {"latitud": 8.2588997, "longitud": -84.9399704}
]

matriz[1][0] = 6     # Cambiar valor 3 en matriz por 6
cantantes[0]["nombre"]: "Enrique Martín Morales" # Cambiar Ricky Martin por EMM
ciudades["México"][2]: "Monterrey" # Cambiar Cancún por Monterrey
coordenadas["latitud"]: 9.9355431

# Iterar a través de una lista de diccionarios
cantantes = [
    {"nombre": "Taylor Swift", "pais": "Estados Unidos"},
    {"nombre": "Tate McRae", "pais": "Canadá"},
    {"nombre": "Adele", "pais": "Reino Unido"},
    {"nombre": "Tyla", "pais": "Sudáfrica"},
    {"nombre": "Aurora", "pais": "Noruega"},
]

def iterarDiccionario(lista):
    for diccionario in lista:
        pares_formateados = []
        for llave, valor in diccionario.items():
            pares_formateados.append(f"{llave}- {valor}")
        print(", ".join(pares_formateados))

iterarDiccionario(cantantes)

# Obtener valores de una lista de diccionarios
def iterarDiccionario2(llave,lista):
    for diccionario in lista:
        print(diccionario[llave])

print(">>> Cantantes <<<")
iterarDiccionario2("nombre",cantantes)
print("\n>>> Paises <<<")
iterarDiccionario2("pais",cantantes)

# Iterar a través de un diccionario con valores de lista
chile = {
    "ciudades": ["Santiago","Viña del Mar","Los Andes"],
    "distintivo": ["capital", "playa", "nieve"]
}

def imprimirInformacion(diccionario):
    for llave, valor in diccionario.items():
        if isinstance(valor, list):
            size = len(valor)
            print(f"{size} {llave.upper()}")
            for elemento in valor:
                print(elemento)
            print("")

imprimirInformacion(chile)

