# -*- coding: utf-8 -*-
"""analisis_ventas_core.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QQkv5_TsS_4T5qHuP5h_y_Gdom2PcIu0
"""

# Carga de datos sobre transacciones financieras
ventas = [
    {"fecha": "2024-01-01", "producto": "ETF S&P 500", "cantidad": 10, "precio": 450.50},
    {"fecha": "2024-01-01", "producto": "Bonos Tesoro US", "cantidad": 5, "precio": 995.00},
    {"fecha": "2024-01-02", "producto": "ETF S&P 500", "cantidad": 15, "precio": 452.00},
    {"fecha": "2024-01-02", "producto": "Acciones AAPL", "cantidad": 50, "precio": 185.20},
    {"fecha": "2024-01-03", "producto": "Bonos Tesoro US", "cantidad": 12, "precio": 998.50},
    {"fecha": "2024-01-03", "producto": "Acciones AAPL", "cantidad": 20, "precio": 188.00}
]

# Cálculo de Ingresos Totales
ingresos_totales = 0

for transaccion in ventas:
  ingreso_venta = transaccion["cantidad"] * transaccion["precio"]
  ingresos_totales += ingreso_venta

# Análisis del Producto más vendido
ventas_por_producto = {}

for transaccion in ventas:
    producto = transaccion["producto"]
    cantidad = transaccion["cantidad"]
    if producto in ventas_por_producto: # Si pcto existe, sumamos cantidad
        ventas_por_producto[producto] += cantidad
    else: # Si no existe, lo inicializamos
        ventas_por_producto[producto] = cantidad

producto_mas_vendido = ""
max_cantidad = 0

for producto, cantidad in ventas_por_producto.items():
    if cantidad > max_cantidad:
        max_cantidad = cantidad
        producto_mas_vendido = producto

precios_por_producto = {}

for transaccion in ventas:
    producto = transaccion["producto"]
    ingreso = transaccion["cantidad"] * transaccion["precio"]
    cantidad = transaccion["cantidad"]

    if producto in precios_por_producto:
        suma_actual, cant_actual = precios_por_producto[producto]
        precios_por_producto[producto] = (suma_actual + ingreso, cant_actual + cantidad)
    else:
        precios_por_producto[producto] = (ingreso, cantidad)

precio_promedio_por_producto = {}
for producto, datos in precios_por_producto.items():
    suma_total = datos[0]
    cant_total = datos[1]
    precio_promedio_por_producto[producto] = suma_total / cant_total

# Ventas por día
ingresos_por_dia = {}

for transaccion in ventas:
    fecha = transaccion["fecha"]
    ingreso = transaccion["cantidad"] * transaccion["precio"]

    if fecha in ingresos_por_dia:
        ingresos_por_dia[fecha] += ingreso
    else:
        ingresos_por_dia[fecha] = ingreso

# Resumen final
resumen_ventas = {}

for producto in ventas_por_producto.keys():
    resumen_ventas[producto] = {
        "cantidad_total": ventas_por_producto[producto],
        "ingresos_totales": precios_por_producto[producto][0], # El índice 0 de la tupla es la suma total
        "precio_promedio": precio_promedio_por_producto[producto]
    }

# Imprimimos información
print("--- REPORTE DE VENTAS ---\n")

print("1. INGRESOS TOTALES DEL PORTAFOLIO:")
print(f"${ingresos_totales:,.2f}\n")

print("2. PRODUCTO MÁS VENDIDO:")
print(f"Producto: {producto_mas_vendido} (Unidades: {max_cantidad})\n")

print("3. INGRESOS POR DÍA:")
for fecha, ingreso in ingresos_por_dia.items():
    print(f"- {fecha}: ${ingreso:,.2f}")
print("\n")

print("4. RESUMEN DE VENTAS POR PRODUCTO:")
for producto, datos in resumen_ventas.items():
    print(f"[{producto.upper()}]")
    print(f"  Cantidad Vendida : {datos['cantidad_total']} unidades")
    print(f"  Ingresos Totales : ${datos['ingresos_totales']:,.2f}")
    print(f"  Precio Promedio  : ${datos['precio_promedio']:,.2f}\n")